services:
  - type: web
    name: flask-english-flashcards
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:10000 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"